export const biomas = [
  {
    tipos: ["normal", "voador"],
    cor: "gray",
    posX: 0,
    posY: 0,
    largura: 600,
    altura: 600,
  },
  {
    tipos: ["agua", "gelo"],
    cor: "blue",
    posX: 0,
    posY: 600,
    largura: 600,
    altura: 800,
  },
  {
    tipos: ["normal", "voador"],
    cor: "gray",
    posX: 0,
    posY: 1400,
    largura: 600,
    altura: 600,
  },
  {
    tipos: ["fogo", "terra", "pedra"],
    cor: "orange",
    posX: 600,
    posY: 0,
    largura: 800,
    altura: 600,
  },
  {
    tipos: ["eletrico", "fantasma", "dragao"],
    cor: "purple",
    posX: 600,
    posY: 600,
    largura: 800,
    altura: 800,
  },
  {
    tipos: ["lutador", "veneno"],
    cor: "brown",
    posX: 600,
    posY: 1400,
    largura: 800,
    altura: 600,
  },
  {
    tipos: ["normal", "voador"],
    cor: "gray",
    posX: 1400,
    posY: 0,
    largura: 600,
    altura: 600,
  },
  {
    tipos: ["grama", "psiquico", "inseto"],
    cor: "green",
    posX: 1400,
    posY: 600,
    largura: 600,
    altura: 800,
  },
  {
    tipos: ["normal", "voador"],
    cor: "gray",
    posX: 1400,
    posY: 1400,
    largura: 600,
    altura: 600,
  },
];

export const obstaculos = [
  // {
  //   posX: 200,
  //   posY: 500,
  //   largura: 100,
  //   altura: 100,
  // },
  // {
  //   posX: 700,
  //   posY: 100,
  //   largura: 150,
  //   altura: 150,
  // },
  // {
  //   posX: 900,
  //   posY: 500,
  //   largura: 100,
  //   altura: 100,
  // },
  // {
  //   posX: 1200,
  //   posY: 1200,
  //   largura: 100,
  //   altura: 100,
  // },
  // {
  //   posX: 400,
  //   posY: 1500,
  //   largura: 200,
  //   altura: 200,
  // },
];
