export const pokedex = [
  {
    pokedex: 1,
    estaAtivo: true,
    especie: "Bulbasaur",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 2, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 2,
    estaAtivo: false,
    especie: "Ivysaur",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 3, especie: "Venusaur", nivel: 40, buff: 40 },
    incremento: 4,
  },
  {
    pokedex: 3,
    estaAtivo: false,
    especie: "Venusaur",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    incremento: 6,
  },
  {
    pokedex: 4,
    estaAtivo: true,
    especie: "Charmander",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 5, especie: "Charmeleon", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 5,
    estaAtivo: false,
    especie: "Charmeleon",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 6, especie: "Charizard", nivel: 40, buff: 40 },
    incremento: 4,
  },
  {
    pokedex: 6,
    estaAtivo: false,
    especie: "Charizard",
    tipos: ["fogo", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    incremento: 6,
  },
  {
    pokedex: 7,
    estaAtivo: true,
    especie: "Squirtle",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 8, especie: "Wartortle", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 8,
    estaAtivo: false,
    especie: "Wartortle",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 9, especie: "Blastoise", nivel: 40, buff: 40 },
    incremento: 4,
  },
  {
    pokedex: 9,
    estaAtivo: false,
    especie: "Blastoise",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    incremento: 6,
  },
  {
    pokedex: 10,
    estaAtivo: true,
    especie: "Caterpie",
    tipos: ["inseto"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 11,
    estaAtivo: false,
    especie: "Metapod",
    tipos: ["inseto"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 12,
    estaAtivo: false,
    especie: "Butterfree",
    tipos: ["inseto", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 13,
    estaAtivo: true,
    especie: "Weedle",
    tipos: ["inseto", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 14,
    estaAtivo: false,
    especie: "Kakuna",
    tipos: ["inseto", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 15,
    estaAtivo: false,
    especie: "Beedrill",
    tipos: ["inseto", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 16,
    estaAtivo: true,
    especie: "Pidgey",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 17,
    estaAtivo: false,
    especie: "Pidgeotto",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 18,
    estaAtivo: false,
    especie: "Pidgeot",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 19,
    estaAtivo: true,
    especie: "Rattata",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 20,
    estaAtivo: false,
    especie: "Raticate",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 21,
    estaAtivo: true,
    especie: "Spearow",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 22,
    estaAtivo: false,
    especie: "Fearow",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 23,
    estaAtivo: true,
    especie: "Ekans",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 24,
    estaAtivo: false,
    especie: "Arbok",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 25,
    estaAtivo: true,
    especie: "Pikachu",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 26,
    estaAtivo: false,
    especie: "Raichu",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 27,
    estaAtivo: true,
    especie: "Sandshrew",
    tipos: ["terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 28,
    estaAtivo: false,
    especie: "Sandslash",
    tipos: ["terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 29,
    estaAtivo: true,
    especie: "Nidoran♀",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 30,
    estaAtivo: false,
    especie: "Nidorina",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 31,
    estaAtivo: false,
    especie: "Nidoqueen",
    tipos: ["veneno", "terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 32,
    estaAtivo: true,
    especie: "Nidoran♂",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 33,
    estaAtivo: false,
    especie: "Nidorino",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 34,
    estaAtivo: false,
    especie: "Nidoking",
    tipos: ["veneno", "terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 35,
    estaAtivo: true,
    especie: "Clefairy",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 36,
    estaAtivo: false,
    especie: "Clefable",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 37,
    estaAtivo: true,
    especie: "Vulpix",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 38,
    estaAtivo: false,
    especie: "Ninetales",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 39,
    estaAtivo: true,
    especie: "Jigglypuff",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 40,
    estaAtivo: false,
    especie: "Wigglytuff",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 41,
    estaAtivo: true,
    especie: "Zubat",
    tipos: ["veneno", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 42,
    estaAtivo: false,
    especie: "Golbat",
    tipos: ["veneno", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 43,
    estaAtivo: true,
    especie: "Oddish",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 44,
    estaAtivo: false,
    especie: "Gloom",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 45,
    estaAtivo: false,
    especie: "Vileplume",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 46,
    estaAtivo: true,
    especie: "Paras",
    tipos: ["inseto", "grama"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 47,
    estaAtivo: false,
    especie: "Parasect",
    tipos: ["inseto", "grama"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 48,
    estaAtivo: true,
    especie: "Venonat",
    tipos: ["inseto", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 49,
    estaAtivo: false,
    especie: "Venomoth",
    tipos: ["inseto", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 50,
    estaAtivo: true,
    especie: "Diglett",
    tipos: ["terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 51,
    estaAtivo: false,
    especie: "Dugtrio",
    tipos: ["terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 52,
    estaAtivo: true,
    especie: "Meowth",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 53,
    estaAtivo: false,
    especie: "Persian",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 54,
    estaAtivo: true,
    especie: "Psyduck",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 55,
    estaAtivo: false,
    especie: "Golduck",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 56,
    estaAtivo: true,
    especie: "Mankey",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 57,
    estaAtivo: false,
    especie: "Primeape",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 58,
    estaAtivo: true,
    especie: "Growlithe",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 59,
    estaAtivo: false,
    especie: "Arcanine",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 60,
    estaAtivo: true,
    especie: "Poliwag",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 61,
    estaAtivo: false,
    especie: "Poliwhirl",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 62,
    estaAtivo: false,
    especie: "Poliwrath",
    tipos: ["agua", "lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 63,
    estaAtivo: true,
    especie: "Abra",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 64,
    estaAtivo: false,
    especie: "Kadabra",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 65,
    estaAtivo: false,
    especie: "Alakazam",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 66,
    estaAtivo: true,
    especie: "Machop",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 67,
    estaAtivo: false,
    especie: "Machoke",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 68,
    estaAtivo: false,
    especie: "Machamp",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 69,
    estaAtivo: true,
    especie: "Bellsprout",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 70,
    estaAtivo: false,
    especie: "Weepinbell",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 71,
    estaAtivo: false,
    especie: "Victreebel",
    tipos: ["grama", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 72,
    estaAtivo: true,
    especie: "Tentacool",
    tipos: ["agua", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 73,
    estaAtivo: false,
    especie: "Tentacruel",
    tipos: ["agua", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 74,
    estaAtivo: true,
    especie: "Geodude",
    tipos: ["pedra", "terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 75,
    estaAtivo: false,
    especie: "Graveler",
    tipos: ["pedra", "terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 76,
    estaAtivo: false,
    especie: "Golem",
    tipos: ["pedra", "terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 77,
    estaAtivo: true,
    especie: "Ponyta",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 78,
    estaAtivo: false,
    especie: "Rapidash",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 79,
    estaAtivo: true,
    especie: "Slowpoke",
    tipos: ["agua", "psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 80,
    estaAtivo: false,
    especie: "Slowbro",
    tipos: ["agua", "psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 81,
    estaAtivo: true,
    especie: "Magnemite",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 82,
    estaAtivo: false,
    especie: "Magneton",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 83,
    estaAtivo: true,
    especie: "Farfetchd",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 84,
    estaAtivo: true,
    especie: "Doduo",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 85,
    estaAtivo: false,
    especie: "Dodrio",
    tipos: ["normal", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 86,
    estaAtivo: true,
    especie: "Seel",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 87,
    estaAtivo: false,
    especie: "Dewgong",
    tipos: ["agua", "gelo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 88,
    estaAtivo: true,
    especie: "Grimer",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 89,
    estaAtivo: false,
    especie: "Muk",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 90,
    estaAtivo: true,
    especie: "Shellder",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 91,
    estaAtivo: false,
    especie: "Cloyster",
    tipos: ["agua", "gelo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 92,
    estaAtivo: true,
    especie: "Gastly",
    tipos: ["fantasma", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 93,
    estaAtivo: false,
    especie: "Haunter",
    tipos: ["fantasma", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 94,
    estaAtivo: false,
    especie: "Gengar",
    tipos: ["fantasma", "veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 95,
    estaAtivo: true,
    especie: "Onix",
    tipos: ["pedra", "terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 96,
    estaAtivo: true,
    especie: "Drowzee",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 97,
    estaAtivo: false,
    especie: "Hypno",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 98,
    estaAtivo: true,
    especie: "Krabby",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 99,
    estaAtivo: false,
    especie: "Kingler",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 100,
    estaAtivo: true,
    especie: "Voltorb",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 101,
    estaAtivo: false,
    especie: "Electrode",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 102,
    estaAtivo: true,
    especie: "Exeggcute",
    tipos: ["grama", "psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 103,
    estaAtivo: false,
    especie: "Exeggutor",
    tipos: ["grama", "psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 104,
    estaAtivo: true,
    especie: "Cubone",
    tipos: ["terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 105,
    estaAtivo: false,
    especie: "Marowak",
    tipos: ["terra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 106,
    estaAtivo: true,
    especie: "Hitmonlee",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 107,
    estaAtivo: true,
    especie: "Hitmonchan",
    tipos: ["lutador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 108,
    estaAtivo: true,
    especie: "Lickitung",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 109,
    estaAtivo: true,
    especie: "Koffing",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 110,
    estaAtivo: false,
    especie: "Weezing",
    tipos: ["veneno"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 111,
    estaAtivo: true,
    especie: "Rhyhorn",
    tipos: ["terra", "pedra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 112,
    estaAtivo: false,
    especie: "Rhydon",
    tipos: ["terra", "pedra"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 113,
    estaAtivo: true,
    especie: "Chansey",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 114,
    estaAtivo: true,
    especie: "Tangela",
    tipos: ["grama"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 115,
    estaAtivo: true,
    especie: "Kangaskhan",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 116,
    estaAtivo: true,
    especie: "Horsea",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 117,
    estaAtivo: false,
    especie: "Seadra",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 118,
    estaAtivo: true,
    especie: "Goldeen",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 119,
    estaAtivo: false,
    especie: "Seaking",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 120,
    estaAtivo: true,
    especie: "Staryu",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 121,
    estaAtivo: false,
    especie: "Starmie",
    tipos: ["agua", "psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 122,
    estaAtivo: true,
    especie: "Mr. Mime",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 123,
    estaAtivo: true,
    especie: "Scyther",
    tipos: ["inseto", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 124,
    estaAtivo: true,
    especie: "Jynx",
    tipos: ["gelo", "psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 125,
    estaAtivo: true,
    especie: "Electabuzz",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 126,
    estaAtivo: true,
    especie: "Magmar",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 127,
    estaAtivo: true,
    especie: "Pinsir",
    tipos: ["inseto"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 128,
    estaAtivo: true,
    especie: "Tauros",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 129,
    estaAtivo: true,
    especie: "Magikarp",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 130,
    estaAtivo: false,
    especie: "Gyarados",
    tipos: ["agua", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 131,
    estaAtivo: true,
    especie: "Lapras",
    tipos: ["agua", "gelo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 132,
    estaAtivo: true,
    especie: "Ditto",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 133,
    estaAtivo: true,
    especie: "Eevee",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 134,
    estaAtivo: false,
    especie: "Vaporeon",
    tipos: ["agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 135,
    estaAtivo: false,
    especie: "Jolteon",
    tipos: ["eletrico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 136,
    estaAtivo: false,
    especie: "Flareon",
    tipos: ["fogo"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 137,
    estaAtivo: true,
    especie: "Porygon",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 138,
    estaAtivo: true,
    especie: "Omanyte",
    tipos: ["pedra", "agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 139,
    estaAtivo: false,
    especie: "Omastar",
    tipos: ["pedra", "agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 140,
    estaAtivo: true,
    especie: "Kabuto",
    tipos: ["pedra", "agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 141,
    estaAtivo: false,
    especie: "Kabutops",
    tipos: ["pedra", "agua"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 142,
    estaAtivo: true,
    especie: "Aerodactyl",
    tipos: ["pedra", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 143,
    estaAtivo: true,
    especie: "Snorlax",
    tipos: ["normal"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 144,
    estaAtivo: true,
    especie: "Articuno",
    tipos: ["gelo", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 145,
    estaAtivo: true,
    especie: "Zapdos",
    tipos: ["eletrico", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 146,
    estaAtivo: true,
    especie: "Moltres",
    tipos: ["fogo", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 147,
    estaAtivo: true,
    especie: "Dratini",
    tipos: ["dragao"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 148,
    estaAtivo: false,
    especie: "Dragonair",
    tipos: ["dragao"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 149,
    estaAtivo: false,
    especie: "Dragonite",
    tipos: ["dragao", "voador"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 150,
    estaAtivo: true,
    especie: "Mewtwo",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
  {
    pokedex: 151,
    estaAtivo: true,
    especie: "Mew",
    tipos: ["psiquico"],
    vidaBase: 100,
    vida: 100,
    ataque: 5,
    defesa: 2,
    ataques: {
      basico: { dano: 8, recarga: 1 },
    },
    evolucao: { pokedex: 1, especie: "Ivysaur", nivel: 15, buff: 20 },
    incremento: 2,
  },
];
