const pokedex = [
  {
    nome: "Bulbasaur",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 1,
  },
  {
    nome: "Ivysaur",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 2,
  },
  {
    nome: "Venusaur",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 3,
  },
  {
    nome: "Charmander",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 4,
  },
  {
    nome: "Charmeleon",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 5,
  },
  {
    nome: "Charizard",
    tipos: ["fogo", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 6,
  },
  {
    nome: "Squirtle",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 7,
  },
  {
    nome: "Wartortle",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 8,
  },
  {
    nome: "Blastoise",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 9,
  },
  {
    nome: "Caterpie",
    tipos: ["inseto"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 10,
  },
  {
    nome: "Metapod",
    tipos: ["inseto"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 11,
  },
  {
    nome: "Butterfree",
    tipos: ["inseto", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 12,
  },
  {
    nome: "Weedle",
    tipos: ["inseto", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 13,
  },
  {
    nome: "Kakuna",
    tipos: ["inseto", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 14,
  },
  {
    nome: "Beedrill",
    tipos: ["inseto", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 15,
  },
  {
    nome: "Pidgey",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 16,
  },
  {
    nome: "Pidgeotto",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 17,
  },
  {
    nome: "Pidgeot",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 18,
  },
  {
    nome: "Rattata",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 19,
  },
  {
    nome: "Raticate",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 20,
  },
  {
    nome: "Spearow",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 21,
  },
  {
    nome: "Fearow",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 22,
  },
  {
    nome: "Ekans",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 23,
  },
  {
    nome: "Arbok",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 24,
  },
  {
    nome: "Pikachu",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 25,
  },
  {
    nome: "Raichu",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 26,
  },
  {
    nome: "Sandshrew",
    tipos: ["terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 27,
  },
  {
    nome: "Sandslash",
    tipos: ["terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 28,
  },
  {
    nome: "Nidoran♀",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 29,
  },
  {
    nome: "Nidorina",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 30,
  },
  {
    nome: "Nidoqueen",
    tipos: ["veneno", "terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 31,
  },
  {
    nome: "Nidoran♂",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 32,
  },
  {
    nome: "Nidorino",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 33,
  },
  {
    nome: "Nidoking",
    tipos: ["veneno", "terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 34,
  },
  {
    nome: "Clefairy",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 35,
  },
  {
    nome: "Clefable",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 36,
  },
  {
    nome: "Vulpix",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 37,
  },
  {
    nome: "Ninetales",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 38,
  },
  {
    nome: "Jigglypuff",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 39,
  },
  {
    nome: "Wigglytuff",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 40,
  },
  {
    nome: "Zubat",
    tipos: ["veneno", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 41,
  },
  {
    nome: "Golbat",
    tipos: ["veneno", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 42,
  },
  {
    nome: "Oddish",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 43,
  },
  {
    nome: "Gloom",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 44,
  },
  {
    nome: "Vileplume",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 45,
  },
  {
    nome: "Paras",
    tipos: ["inseto", "grama"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 46,
  },
  {
    nome: "Parasect",
    tipos: ["inseto", "grama"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 47,
  },
  {
    nome: "Venonat",
    tipos: ["inseto", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 48,
  },
  {
    nome: "Venomoth",
    tipos: ["inseto", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 49,
  },
  {
    nome: "Diglett",
    tipos: ["terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 50,
  },
  {
    nome: "Dugtrio",
    tipos: ["terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 51,
  },
  {
    nome: "Meowth",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 52,
  },
  {
    nome: "Persian",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 53,
  },
  {
    nome: "Psyduck",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 54,
  },
  {
    nome: "Golduck",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 55,
  },
  {
    nome: "Mankey",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 56,
  },
  {
    nome: "Primeape",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 57,
  },
  {
    nome: "Growlithe",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 58,
  },
  {
    nome: "Arcanine",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 59,
  },
  {
    nome: "Poliwag",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 60,
  },
  {
    nome: "Poliwhirl",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 61,
  },
  {
    nome: "Poliwrath",
    tipos: ["agua", "lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 62,
  },
  {
    nome: "Abra",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 63,
  },
  {
    nome: "Kadabra",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 64,
  },
  {
    nome: "Alakazam",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 65,
  },
  {
    nome: "Machop",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 66,
  },
  {
    nome: "Machoke",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 67,
  },
  {
    nome: "Machamp",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 68,
  },
  {
    nome: "Bellsprout",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 69,
  },
  {
    nome: "Weepinbell",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 70,
  },
  {
    nome: "Victreebel",
    tipos: ["grama", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 71,
  },
  {
    nome: "Tentacool",
    tipos: ["agua", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 72,
  },
  {
    nome: "Tentacruel",
    tipos: ["agua", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 73,
  },
  {
    nome: "Geodude",
    tipos: ["pedra", "terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 74,
  },
  {
    nome: "Graveler",
    tipos: ["pedra", "terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 75,
  },
  {
    nome: "Golem",
    tipos: ["pedra", "terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 76,
  },
  {
    nome: "Ponyta",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 77,
  },
  {
    nome: "Rapidash",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 78,
  },
  {
    nome: "Slowpoke",
    tipos: ["agua", "psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 79,
  },
  {
    nome: "Slowbro",
    tipos: ["agua", "psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 80,
  },
  {
    nome: "Magnemite",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 81,
  },
  {
    nome: "Magneton",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 82,
  },
  {
    nome: "Farfetch'd",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 83,
  },
  {
    nome: "Doduo",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 84,
  },
  {
    nome: "Dodrio",
    tipos: ["normal", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 85,
  },
  {
    nome: "Seel",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 86,
  },
  {
    nome: "Dewgong",
    tipos: ["agua", "gelo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 87,
  },
  {
    nome: "Grimer",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 88,
  },
  {
    nome: "Muk",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 89,
  },
  {
    nome: "Shellder",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 90,
  },
  {
    nome: "Cloyster",
    tipos: ["agua", "gelo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 91,
  },
  {
    nome: "Gastly",
    tipos: ["fantasma", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 92,
  },
  {
    nome: "Haunter",
    tipos: ["fantasma", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 93,
  },
  {
    nome: "Gengar",
    tipos: ["fantasma", "veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 94,
  },
  {
    nome: "Onix",
    tipos: ["pedra", "terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 95,
  },
  {
    nome: "Drowzee",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 96,
  },
  {
    nome: "Hypno",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 97,
  },
  {
    nome: "Krabby",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 98,
  },
  {
    nome: "Kingler",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 99,
  },
  {
    nome: "Voltorb",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 100,
  },
  {
    nome: "Electrode",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 101,
  },
  {
    nome: "Exeggcute",
    tipos: ["grama", "psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 102,
  },
  {
    nome: "Exeggutor",
    tipos: ["grama", "psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 103,
  },
  {
    nome: "Cubone",
    tipos: ["terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 104,
  },
  {
    nome: "Marowak",
    tipos: ["terra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 105,
  },
  {
    nome: "Hitmonlee",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 106,
  },
  {
    nome: "Hitmonchan",
    tipos: ["lutador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 107,
  },
  {
    nome: "Lickitung",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 108,
  },
  {
    nome: "Koffing",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 109,
  },
  {
    nome: "Weezing",
    tipos: ["veneno"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 110,
  },
  {
    nome: "Rhyhorn",
    tipos: ["terra", "pedra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 111,
  },
  {
    nome: "Rhydon",
    tipos: ["terra", "pedra"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 112,
  },
  {
    nome: "Chansey",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 113,
  },
  {
    nome: "Tangela",
    tipos: ["grama"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 114,
  },
  {
    nome: "Kangaskhan",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 115,
  },
  {
    nome: "Horsea",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 116,
  },
  {
    nome: "Seadra",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 117,
  },
  {
    nome: "Goldeen",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 118,
  },
  {
    nome: "Seaking",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 119,
  },
  {
    nome: "Staryu",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 120,
  },
  {
    nome: "Starmie",
    tipos: ["agua", "psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 121,
  },
  {
    nome: "Mr. Mime",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 122,
  },
  {
    nome: "Scyther",
    tipos: ["inseto", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 123,
  },
  {
    nome: "Jynx",
    tipos: ["gelo", "psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 124,
  },
  {
    nome: "Electabuzz",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 125,
  },
  {
    nome: "Magmar",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 126,
  },
  {
    nome: "Pinsir",
    tipos: ["inseto"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 127,
  },
  {
    nome: "Tauros",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 128,
  },
  {
    nome: "Magikarp",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 129,
  },
  {
    nome: "Gyarados",
    tipos: ["agua", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 130,
  },
  {
    nome: "Lapras",
    tipos: ["agua", "gelo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 131,
  },
  {
    nome: "Ditto",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 132,
  },
  {
    nome: "Eevee",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 133,
  },
  {
    nome: "Vaporeon",
    tipos: ["agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 134,
  },
  {
    nome: "Jolteon",
    tipos: ["eletrico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 135,
  },
  {
    nome: "Flareon",
    tipos: ["fogo"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 136,
  },
  {
    nome: "Porygon",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 137,
  },
  {
    nome: "Omanyte",
    tipos: ["pedra", "agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 138,
  },
  {
    nome: "Omastar",
    tipos: ["pedra", "agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 139,
  },
  {
    nome: "Kabuto",
    tipos: ["pedra", "agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 140,
  },
  {
    nome: "Kabutops",
    tipos: ["pedra", "agua"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 141,
  },
  {
    nome: "Aerodactyl",
    tipos: ["pedra", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 142,
  },
  {
    nome: "Snorlax",
    tipos: ["normal"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 143,
  },
  {
    nome: "Articuno",
    tipos: ["gelo", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 144,
  },
  {
    nome: "Zapdos",
    tipos: ["eletrico", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 145,
  },
  {
    nome: "Moltres",
    tipos: ["fogo", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 146,
  },
  {
    nome: "Dratini",
    tipos: ["Dragão"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 147,
  },
  {
    nome: "Dragonair",
    tipos: ["Dragão"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 148,
  },
  {
    nome: "Dragonite",
    tipos: ["Dragão", "voador"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 149,
  },
  {
    nome: "Mewtwo",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 150,
  },
  {
    nome: "Mew",
    tipos: ["psíquico"],
    hp: 100,
    ataque: 10,
    defesa: 6,
    atkSpeed: 1,
    numeroPokedex: 151,
  },
];

return pokedex;
