export const pokedex = [
  {
    especie: "Bulbasaur",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 1,
  },
  {
    especie: "Ivysaur",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 2,
  },
  {
    especie: "Venusaur",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 3,
  },
  {
    especie: "Charmander",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 4,
  },
  {
    especie: "Charmeleon",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 5,
  },
  {
    especie: "Charizard",
    tipos: ["fogo", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 6,
  },
  {
    especie: "Squirtle",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 7,
  },
  {
    especie: "Wartortle",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 8,
  },
  {
    especie: "Blastoise",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 9,
  },
  {
    especie: "Caterpie",
    tipos: ["inseto"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 10,
  },
  {
    especie: "Metapod",
    tipos: ["inseto"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 11,
  },
  {
    especie: "Butterfree",
    tipos: ["inseto", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 12,
  },
  {
    especie: "Weedle",
    tipos: ["inseto", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 13,
  },
  {
    especie: "Kakuna",
    tipos: ["inseto", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 14,
  },
  {
    especie: "Beedrill",
    tipos: ["inseto", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 15,
  },
  {
    especie: "Pidgey",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 16,
  },
  {
    especie: "Pidgeotto",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 17,
  },
  {
    especie: "Pidgeot",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 18,
  },
  {
    especie: "Rattata",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 19,
  },
  {
    especie: "Raticate",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 20,
  },
  {
    especie: "Spearow",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 21,
  },
  {
    especie: "Fearow",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 22,
  },
  {
    especie: "Ekans",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 23,
  },
  {
    especie: "Arbok",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 24,
  },
  {
    especie: "Pikachu",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 25,
  },
  {
    especie: "Raichu",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 26,
  },
  {
    especie: "Sandshrew",
    tipos: ["terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 27,
  },
  {
    especie: "Sandslash",
    tipos: ["terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 28,
  },
  {
    especie: "Nidoran♀",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 29,
  },
  {
    especie: "Nidorina",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 30,
  },
  {
    especie: "Nidoqueen",
    tipos: ["veneno", "terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 31,
  },
  {
    especie: "Nidoran♂",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 32,
  },
  {
    especie: "Nidorino",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 33,
  },
  {
    especie: "Nidoking",
    tipos: ["veneno", "terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 34,
  },
  {
    especie: "Clefairy",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 35,
  },
  {
    especie: "Clefable",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 36,
  },
  {
    especie: "Vulpix",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 37,
  },
  {
    especie: "Ninetales",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 38,
  },
  {
    especie: "Jigglypuff",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 39,
  },
  {
    especie: "Wigglytuff",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 40,
  },
  {
    especie: "Zubat",
    tipos: ["veneno", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 41,
  },
  {
    especie: "Golbat",
    tipos: ["veneno", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 42,
  },
  {
    especie: "Oddish",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 43,
  },
  {
    especie: "Gloom",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 44,
  },
  {
    especie: "Vileplume",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 45,
  },
  {
    especie: "Paras",
    tipos: ["inseto", "grama"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 46,
  },
  {
    especie: "Parasect",
    tipos: ["inseto", "grama"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 47,
  },
  {
    especie: "Venonat",
    tipos: ["inseto", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 48,
  },
  {
    especie: "Venomoth",
    tipos: ["inseto", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 49,
  },
  {
    especie: "Diglett",
    tipos: ["terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 50,
  },
  {
    especie: "Dugtrio",
    tipos: ["terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 51,
  },
  {
    especie: "Meowth",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 52,
  },
  {
    especie: "Persian",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 53,
  },
  {
    especie: "Psyduck",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 54,
  },
  {
    especie: "Golduck",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 55,
  },
  {
    especie: "Mankey",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 56,
  },
  {
    especie: "Primeape",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 57,
  },
  {
    especie: "Growlithe",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 58,
  },
  {
    especie: "Arcanine",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 59,
  },
  {
    especie: "Poliwag",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 60,
  },
  {
    especie: "Poliwhirl",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 61,
  },
  {
    especie: "Poliwrath",
    tipos: ["agua", "lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 62,
  },
  {
    especie: "Abra",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 63,
  },
  {
    especie: "Kadabra",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 64,
  },
  {
    especie: "Alakazam",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 65,
  },
  {
    especie: "Machop",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 66,
  },
  {
    especie: "Machoke",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 67,
  },
  {
    especie: "Machamp",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 68,
  },
  {
    especie: "Bellsprout",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 69,
  },
  {
    especie: "Weepinbell",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 70,
  },
  {
    especie: "Victreebel",
    tipos: ["grama", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 71,
  },
  {
    especie: "Tentacool",
    tipos: ["agua", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 72,
  },
  {
    especie: "Tentacruel",
    tipos: ["agua", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 73,
  },
  {
    especie: "Geodude",
    tipos: ["pedra", "terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 74,
  },
  {
    especie: "Graveler",
    tipos: ["pedra", "terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 75,
  },
  {
    especie: "Golem",
    tipos: ["pedra", "terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 76,
  },
  {
    especie: "Ponyta",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 77,
  },
  {
    especie: "Rapidash",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 78,
  },
  {
    especie: "Slowpoke",
    tipos: ["agua", "psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 79,
  },
  {
    especie: "Slowbro",
    tipos: ["agua", "psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 80,
  },
  {
    especie: "Magnemite",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 81,
  },
  {
    especie: "Magneton",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 82,
  },
  {
    especie: "Farfetch'd",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 83,
  },
  {
    especie: "Doduo",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 84,
  },
  {
    especie: "Dodrio",
    tipos: ["normal", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 85,
  },
  {
    especie: "Seel",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 86,
  },
  {
    especie: "Dewgong",
    tipos: ["agua", "gelo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 87,
  },
  {
    especie: "Grimer",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 88,
  },
  {
    especie: "Muk",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 89,
  },
  {
    especie: "Shellder",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 90,
  },
  {
    especie: "Cloyster",
    tipos: ["agua", "gelo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 91,
  },
  {
    especie: "Gastly",
    tipos: ["fantasma", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 92,
  },
  {
    especie: "Haunter",
    tipos: ["fantasma", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 93,
  },
  {
    especie: "Gengar",
    tipos: ["fantasma", "veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 94,
  },
  {
    especie: "Onix",
    tipos: ["pedra", "terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 95,
  },
  {
    especie: "Drowzee",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 96,
  },
  {
    especie: "Hypno",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 97,
  },
  {
    especie: "Krabby",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 98,
  },
  {
    especie: "Kingler",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 99,
  },
  {
    especie: "Voltorb",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 100,
  },
  {
    especie: "Electrode",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 101,
  },
  {
    especie: "Exeggcute",
    tipos: ["grama", "psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 102,
  },
  {
    especie: "Exeggutor",
    tipos: ["grama", "psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 103,
  },
  {
    especie: "Cubone",
    tipos: ["terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 104,
  },
  {
    especie: "Marowak",
    tipos: ["terra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 105,
  },
  {
    especie: "Hitmonlee",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 106,
  },
  {
    especie: "Hitmonchan",
    tipos: ["lutador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 107,
  },
  {
    especie: "Lickitung",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 108,
  },
  {
    especie: "Koffing",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 109,
  },
  {
    especie: "Weezing",
    tipos: ["veneno"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 110,
  },
  {
    especie: "Rhyhorn",
    tipos: ["terra", "pedra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 111,
  },
  {
    especie: "Rhydon",
    tipos: ["terra", "pedra"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 112,
  },
  {
    especie: "Chansey",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 113,
  },
  {
    especie: "Tangela",
    tipos: ["grama"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 114,
  },
  {
    especie: "Kangaskhan",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 115,
  },
  {
    especie: "Horsea",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 116,
  },
  {
    especie: "Seadra",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 117,
  },
  {
    especie: "Goldeen",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 118,
  },
  {
    especie: "Seaking",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 119,
  },
  {
    especie: "Staryu",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 120,
  },
  {
    especie: "Starmie",
    tipos: ["agua", "psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 121,
  },
  {
    especie: "Mr. Mime",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 122,
  },
  {
    especie: "Scyther",
    tipos: ["inseto", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 123,
  },
  {
    especie: "Jynx",
    tipos: ["gelo", "psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 124,
  },
  {
    especie: "Electabuzz",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 125,
  },
  {
    especie: "Magmar",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 126,
  },
  {
    especie: "Pinsir",
    tipos: ["inseto"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 127,
  },
  {
    especie: "Tauros",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 128,
  },
  {
    especie: "Magikarp",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 129,
  },
  {
    especie: "Gyarados",
    tipos: ["agua", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 130,
  },
  {
    especie: "Lapras",
    tipos: ["agua", "gelo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 131,
  },
  {
    especie: "Ditto",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 132,
  },
  {
    especie: "Eevee",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 133,
  },
  {
    especie: "Vaporeon",
    tipos: ["agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 134,
  },
  {
    especie: "Jolteon",
    tipos: ["eletrico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 135,
  },
  {
    especie: "Flareon",
    tipos: ["fogo"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 136,
  },
  {
    especie: "Porygon",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 137,
  },
  {
    especie: "Omanyte",
    tipos: ["pedra", "agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 138,
  },
  {
    especie: "Omastar",
    tipos: ["pedra", "agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 139,
  },
  {
    especie: "Kabuto",
    tipos: ["pedra", "agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 140,
  },
  {
    especie: "Kabutops",
    tipos: ["pedra", "agua"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 141,
  },
  {
    especie: "Aerodactyl",
    tipos: ["pedra", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 142,
  },
  {
    especie: "Snorlax",
    tipos: ["normal"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 143,
  },
  {
    especie: "Articuno",
    tipos: ["gelo", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 144,
  },
  {
    especie: "Zapdos",
    tipos: ["eletrico", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 145,
  },
  {
    especie: "Moltres",
    tipos: ["fogo", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 146,
  },
  {
    especie: "Dratini",
    tipos: ["dragao"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 147,
  },
  {
    especie: "Dragonair",
    tipos: ["dragao"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 148,
  },
  {
    especie: "Dragonite",
    tipos: ["dragao", "voador"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 149,
  },
  {
    especie: "Mewtwo",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 150,
  },
  {
    especie: "Mew",
    tipos: ["psiquico"],
    vida: 100,
    ataque: 10,
    defesa: 6,
    ataques: {
      basico: { dano: 10, recarga: 1 },
      habilidade: { dano: 20, recarga: 5 },
    },
    evolucao: 15,
    incremento: 2,
    numeroPokedex: 151,
  },
];
